grammar Reversetemplate;
parseTpl:every;
every : .*?EOF;
LeftDim: '{{';
RightDim: '}}';
Empty:LeftDim ?Space*?RightDim;
Loop:'{{loop'.*?'}}';
End: '{{end}}';
Gjson:'{{gjson'.*?'}}'; 
Str:(~[{}])+;
Path: [a-zA-Z0-9_.]+;
Space:[\t\r\n\f]+;
